# Generated by Django 4.0.6 on 2023-03-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hongmingstone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='batchID',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='construction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='construction',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
