# Generated by Django 4.0.6 on 2023-04-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hongmingstone', '0003_alter_client_name_alter_worker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionitem',
            name='item',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
