# Generated by Django 4.0.6 on 2022-07-24 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='客戶名稱')),
            ],
            options={
                'db_table': 'tb_client',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='師傅')),
            ],
            options={
                'db_table': 'tb_worker',
            },
        ),
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_site', models.CharField(max_length=200, null=True)),
                ('Construction_item', models.CharField(max_length=200, null=True)),
                ('Construction_cm', models.FloatField(null=True)),
                ('Construction_unit', models.FloatField(null=True)),
                ('Worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='polls.worker')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='polls.client')),
            ],
            options={
                'db_table': 'tb_construction',
            },
        ),
    ]
