# Generated by Django 4.0.6 on 2022-08-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='construction_amount',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='construction',
            name='construction_length',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='construction',
            name='construction_split',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='construction',
            name='construction_unit',
            field=models.FloatField(default=None, null=True),
        ),
    ]
