# Generated by Django 4.0.6 on 2022-09-14 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_client_name_alter_worker_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
