# Generated by Django 4.0.6 on 2022-09-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_construction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2022-09-25 16:39:59', null=True),
        ),
    ]
